language: perl
sudo: false

install:
  - cpanm -n autodie Alien::TinyCC Archive::Ar File::chdir Path::Tiny IPC::System::Simple File::ShareDir::Dist Test2::API Test2::V0
  - cpanm -n FFI::Platypus FFI::Platypus::Type::StringArray
  - perl -Iinc -MMy::DLL -e tcc_build

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script:
  - prove -PShareDirDist -lv

