language: perl
sudo: false

install:
  - cpanm autodie Alien::TinyCC Archive::Ar File::chdir Path::Class IPC::System::Simple File::ShareDir::Dist
  - cpanm FFI::Platypus FFI::Platypus::Type::StringArray
  - perl -Iinc -MMy::DLL -e tcc_build

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - prove -lv

